### ISSUE TITLE
[Feature Request] Hass.io (Operating System) Add-on + Usability concerns

### ISSUE THREAD

**Issue by Jolanrensen** [dennisschroeder/khome#39]
First of all, I'd like to say thank you and well done!
I'm a great Kotlin fan myself and while I was using AppDaemon for my automations, all this loosely typed nonsense is driving me nuts. I'm very interested to be able to automate parts of my home using a proper programming language like Kotlin. 
I am wondering however how you're currently running khome to test it. I understand it can be run from any device that can run Java, so running it from hass.io shouldn't be a problem. However, hass.io does however require an add-on (because of docker and such) to be able to run it, turn it on/off and update it eventually (like AppDaemon).
So that's my humble request for now, other than that, keep up the terrific work :D 

Edit: I am a bit curious why it is necessary to create all these classes for simple actions like turning on a certain light. I mean, shouldn't 
```
callService(TurnOn(Light("wall_lamp")))
// Or even
Light("wall_lamp").turnOn()
```
be a lot easier and lower the learning curve from the python people we're trying to convince to switch?
I assume it's necessary for that Koin stuff, but it does increase the difficulty of using it a lot I think.
Anyways I'll have to play with it to be sure of course.

Edit2: After playing around a bit, I do think that using Koin to make the code more DSL like is hurting the actual usability of the library. To turn off, say 10 light, instead of just creating Light objects from a list of entities and turning those off with a single forloop, now I'd have to create a class for any light in the house, plus for each light a TurnOffLight and TurnOnLight class, I'd have to register them all as beans and then I'd have to callService<>() manually for each light!
Plus, when I add a new light, I'd have to do it all again!
I think some things of your library are great and the amount of work you've put into it is clear, but I think it wouldn't hurt to pursue a simpler approach, like AppDaemon. Abstract away from the service calls and make entities instances. At least that's how I would do it.

**Comment by dennisschroeder** [comment]
**Dear @Jolanrensen,**

first of all, thank you for your kind words. Your precisely describe my motivation to write khome:

> all this loosely typed nonsense is driving me nuts.

I actually run my khome applications in an docker environment. Using gradle to build an shadowJar, and build my docker image with it. I will think about the Hass.io addon idea.

That´s it for now. I will resume to answer your edit2 request later. I can say there is a reason why I choosed the koin way which has a benefit.

**Comment by Jolanrensen** [comment]
Thanks for your response!
And sure, take your time.
I'm actually working on a Kotlin implementation for Hass myself now, but in a way that for the end user it would be as easy to understand as possible, so in the way I described:
```kotlin
class MyAutomation : Automation() {
    val bed = Light("bed")
    val bedroomLamp = Light("bedroom_lamp")
    val lights = listOf(bed, bedroomLamp)

    override suspend fun initialize() {
        Switch("bedroom_switch")
            .onTurnOn {  // this: Switch
                if (lights.any { it.isOn() })
                    lights.forEach { it.turnOff() }
                else
                    lights.forEach { it.turnOn() }

                turnOff()
            }
    }
}
```
Attributes would be available via `bedroomLamp.getAttributes().brightness` or `bedroomLamp.getAttributes()["unsupported_attr"]`.
Service calls are thus directly called from Entities (I'm still thinking about Services in general).
Listeners are automatically defined and registered from the initialize function and anything it calls.
Calls like isOn(), getAttributes() (or getState()) all get the state/attr from hass using a suspend fun so that the async calls can be expressed synchronously.
Anyways, these are just ideas and only the basis is implemented for now. But I'm still curious why you chose Koin as I might have missed something thinking through the idea of my implementation.

**Comment by dennisschroeder** [comment]
Hey, why don't we put our efforts together and create one solution in Kotlin. I already recognized, that having to create one service class for one entity is way to verbose and I am working on a better solution right now. Why don't we work together on it?

The reason why I introduced koin into Khome (which wasn't planned from the beginning) is that I wanted to take over the control of all the entity and service classes for security reasons. Because on startup I check if the entity really exists and if an Service that I want to call, really exists in my hass application.

Let's assume you have a smoke detector in your kitchen. 

```kotlin

class SmokeKitchenBinarySensor("smoke_detector_kitschen")

onStateChange<SmokeKitchenSensor> {
  if(state == "on") callService<NotifyMe>()
}
```
In one of my first versions, the misspelling in the entity name (kitschen => kitchen) will never be detected. You start your application and everything is fine. But the listener will never be executed because there is no **binary_sensor.smoke_detector_kitschen** in my homeassistant instance. So I wanted the system to fail fast to be safe.

So I'm doing this after I pulled a list of all entities from my homeassistant instance:

```kotlin
init {
        if (id !in stateStore) throw EntityNotFoundException("Could not get data for entity: $id")
    }
```

Same with the services. I pull all available services from my homeassistant instance at application start and check if the domains and services under the domains are available to be called from the application I'm building.

I would love to have a little chat over google hangout to show u all the details of khome and discuss your ideas.

**Comment by Jolanrensen** [comment]
Checking whether entity IDs exist is actually a valid security concern I hadn't thought about yet! But I think we might be able to check entity IDs on the fly. That's because most (if not all) of the state listeners and are created at the initialization of the automation by the user, so they'll see the entity ID is wrong before something bad is missed.
In my version an exception could be thrown whenever an entity is created like Light.Entity("wall_lamp") or Entity("switch", "light_switch").
(Again these are just ideas)
As long as I don't allow listening for entity states without wrapping them in some type of Entity class a check can be put in.

As for working together / calling I am a fan! However I do have to keep myself back a bit on this project for a few weeks due to upcoming exams at University, so I'll get back to that in a few weeks. 
Until then I'll keep thinking a bit more about the structure etc, which we can then compare/merge maybe.
My project currently is a kotlin multiplatform library, because why not. 
The KHomeAssistant (hey, I'm not gonna steal your name XD) instance can be created with instances of classes extending Automation (can also be created functionally) and host, port etc. It can also be called without listeners which will terminate the instance whenever all the automations are executed (that's the plan), which will make it a way more useful library.

**Comment by Jolanrensen** [comment]
You can actually resolve the issue btw if you like. I see you've made some promising progress the last couple of months! 

Actually, based on the ideas I've come up with in this issue, for the last couple of months I've been making a Home Assistant library in Kotlin myself as well. Just for fun really.

It's of course in no way competing with yours I hope. It's just a different take on it I suppose. Anyways, maybe it might inspire you as you inspired me. It's of course still a work in progress but I think it might be easier for people jumping ship from AppDaemon.
It can be found at my GitHub: 
https://github.com/Jolanrensen/KHomeAssistant
